apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory
  name: inventory-http
spec:
  ports:
  - name: "http"
    port: 3006
    #the protocol here is TCP because inside the cluster all communication occurs via TCP
    #i.e. this service communicates with its pod via TCP (i.e. it routes the traffic from its port 3004 to the port 3004 on the pod using TCP)
    protocol: TCP
    targetPort: 3006
  selector:
    app: inventory
  type: NodePort

