apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments
spec:
  ports:
  - name: "tcp"
    port: 3001
    #this service will direct traffic from port 3001 (on the service itself) to the pod port 3001
    #(actually the 3001 port is not of the pod but of the container inside the pod), but to the service from the outside it looks as if 
    #that port belongs to the pod (when in reality the pod is simply fronting the port of the container inside it)
    protocol: TCP
    targetPort: 3001
  selector:
    app: payments
  type: ClusterIP

