apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/sleepr-443603/notifications/production
        name: notifications
        env:
         - name: PORT
           value: '3000'
         - name: GOOGLE_OAUTH_CLIENT_ID
           value: 856900899056-ndbg0lvesul1aufpjdoudhvjsslukj9i.apps.googleusercontent.com
         - name: SMTP_USER
           value: nitrox919@gmail.com
         - name: GOOGLE_OAUTH_CLIENT_SECRET
           valueFrom:
            secretKeyRef: 
              name: google
              key: clientSecret
         - name: GOOGLE_OAUTH_REFRESH_TOKEN
           valueFrom:
            secretKeyRef: 
              name: google
              key: refreshToken
        ports:
        #this is the actual container port, that any external service (like the notifications kubernetes service or others) can access in order to get access to the notifications container
        #i.e. this is the port on the notifications container itself, the pod wrapper around the container is responsible for exposing the container to other services
        #specifying this tells the pod which container to expose (via the port on the container)
         - containerPort: 3000
