apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  #this is the actual port from which external services can access this pod
  #while the target port (TCP) is the port on the notifications pod (to which the service communicates and passes on the load/requests)
  - name: "tcp"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: notifications
  type: ClusterIP

