apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-tcp
spec:
  ports:
  - name: "tcp"
    port: 3002
    #the protocol here is TCP because inside the cluster all communication occurs via TCP
    #i.e. this service communicates with its pod via TCP (i.e. it routes the traffic from its port 3002 to the port 3002 on the pod using TCP)
    protocol: TCP
    targetPort: 3002
  selector:
    #app is the name of the pod this service targets i.e. i am using the label app here in order to group the pod and the service
    app: auth
  type: ClusterIP

