apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sales
  name: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/sleepr-443603/sales/production
        name: sales
        env:
        - name: MONGODB_URI
          valueFrom: 
            secretKeyRef:
              name: mongodb
              key: connectionString
        - name: PORT
          value: '3005'
        - name: AUTH_HOST
        #put the name of the auth service here
          value: auth-tcp 
        - name: AUTH_PORT
          value: '3002'
        - name: PAYMENTS_HOST
          value: payments
        - name: PAYMENTS_PORT
          value: '3001'
        - name: INVENTORY_PORT
          value: '3007'
        - name: INVENTORY_HOST
          value: inventory-tcp
        ports:
         - containerPort: 3005
            
